# Generated by Django 5.2 on 2025-04-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(default='default.jpg', upload_to='posts_imgs/'),
        ),
    ]
