# Generated by Django 5.2 on 2025-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='content',
            new_name='post_content',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
        migrations.AddField(
            model_name='posts',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
